development:
  adapter: postgresql
  encoding: unicode
  database: sgcreditcard_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: sgcreditcard_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sgcreditcard_production
  username: postgres
  password: 'pizzasenha#13'
  host: localhost
  pool: 5
